/* eslint-disable */
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async isDebug() : Promise<boolean> {
    return await TAURI_INVOKE("is_debug");
},
async openLogFile() : Promise<null> {
    return await TAURI_INVOKE("open_log_file");
},
async isDirectory(pathStr: string) : Promise<boolean> {
    return await TAURI_INVOKE("is_directory", { pathStr });
},
/**
 * Returns the file size in number of bytes formatted as string,
 * because the numbers might get too large for a `u32`.
 */
async getFileSize(pathStr: string) : Promise<string> {
    return await TAURI_INVOKE("get_file_size", { pathStr });
},
async detectIniPath(gamePath: string | null) : Promise<string | null> {
    return await TAURI_INVOKE("detect_ini_path", { gamePath });
},
async detectIniPrefix(iniPath: string | null) : Promise<string> {
    return await TAURI_INVOKE("detect_ini_prefix", { iniPath });
},
async detectGamePath() : Promise<string[]> {
    return await TAURI_INVOKE("detect_game_path");
},
async validateGamePath(pathStr: string) : Promise<boolean> {
    return await TAURI_INVOKE("validate_game_path", { pathStr });
},
async getSettings() : Promise<Settings> {
    return await TAURI_INVOKE("get_settings");
},
async saveSettings(settings: Settings) : Promise<null> {
    return await TAURI_INVOKE("save_settings", { settings });
},
async getProfiles() : Promise<Profiles> {
    return await TAURI_INVOKE("get_profiles");
},
async saveProfiles(profiles: Profiles) : Promise<null> {
    return await TAURI_INVOKE("save_profiles", { profiles });
},
async fcmPreviewRemove(gamePath: string, iniPath: string, iniPrefix: string) : Promise<FcmPreview> {
    return await TAURI_INVOKE("fcm_preview_remove", { gamePath, iniPath, iniPrefix });
},
async fcmDetectImport(paths: string[]) : Promise<boolean> {
    return await TAURI_INVOKE("fcm_detect_import", { paths });
},
async fcmProbePrerequisites(gamePath: string) : Promise<FcmPrerequisites> {
    return await TAURI_INVOKE("fcm_probe_prerequisites", { gamePath });
},
async fcmPrerequisiteDownloadLinks(apiKey: string, modId: number, fileId: number) : Promise<NexusModsDownloadLink[]> {
    return await TAURI_INVOKE("fcm_prerequisite_download_links", { apiKey, modId, fileId });
},
async fcmPreviewImport(gamePath: string, iniPath: string, iniPrefix: string, paths: string[], selectedProvider: string | null, providerPackage: string | null, loaderPackage: string | null) : Promise<FcmPreview> {
    return await TAURI_INVOKE("fcm_preview_import", { gamePath, iniPath, iniPrefix, paths, selectedProvider, providerPackage, loaderPackage });
},
async fcmApply(token: string) : Promise<string> {
    return await TAURI_INVOKE("fcm_apply", { token });
},
async nexusmodsApiValidate(apiKey: string) : Promise<NexusModsAccountInfo> {
    return await TAURI_INVOKE("nexusmods_api_validate", { apiKey });
},
async nexusmodsApiListModFiles(apiKey: string, gameDomain: string, gameScopedId: number, category: FileCategory) : Promise<NexusModsModFiles> {
    return await TAURI_INVOKE("nexusmods_api_list_mod_files", { apiKey, gameDomain, gameScopedId, category });
},
async nexusmodsApiRequestDownloadLinks(apiKey: string, nxmLink: string) : Promise<NexusModsDownloadLink[]> {
    return await TAURI_INVOKE("nexusmods_api_request_download_links", { apiKey, nxmLink });
},
async nexusmodsGetAccountInfo() : Promise<NexusModsAccountInfo | null> {
    return await TAURI_INVOKE("nexusmods_get_account_info");
},
async nexusmodsSetAccountInfo(accountInfo: NexusModsAccountInfo) : Promise<null> {
    return await TAURI_INVOKE("nexusmods_set_account_info", { accountInfo });
},
async nexusmodsDeleteAccountInfo() : Promise<null> {
    return await TAURI_INVOKE("nexusmods_delete_account_info");
},
async nexusmodsLoginViaSso() : Promise<null> {
    return await TAURI_INVOKE("nexusmods_login_via_sso");
},
async nexusmodsExtractDetailsFromNxmUrl(nxmLink: string) : Promise<NXMLinkDetails> {
    return await TAURI_INVOKE("nexusmods_extract_details_from_nxm_url", { nxmLink });
},
async nxmGetCurrent() : Promise<string | null> {
    return await TAURI_INVOKE("nxm_get_current");
},
async nxmRegister() : Promise<null> {
    return await TAURI_INVOKE("nxm_register");
},
async nxmIsRegistered() : Promise<boolean> {
    return await TAURI_INVOKE("nxm_is_registered");
},
async saveTranslation(fileName: string, translation: Translation) : Promise<null> {
    return await TAURI_INVOKE("save_translation", { fileName, translation });
},
async loadTranslation(key: string) : Promise<Translation> {
    return await TAURI_INVOKE("load_translation", { key });
},
async loadAllTranslationMetadata() : Promise<SerializableCommandResult<TranslationMeta>[]> {
    return await TAURI_INVOKE("load_all_translation_metadata");
},
async downloadWithProgress(downloadUrl: string, downloadFolder: string) : Promise<string> {
    return await TAURI_INVOKE("download_with_progress", { downloadUrl, downloadFolder });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
downloadProgress: DownloadProgress,
nxmNewLink: NXMNewLink,
ssoAbort: NexusModsSSOAbort,
ssoUpdate: NexusModsSSOUpdate
}>({
downloadProgress: "download-progress",
nxmNewLink: "nxm-new-link",
ssoAbort: "sso-abort",
ssoUpdate: "sso-update"
})

/** user-defined constants **/



/** user-defined types **/

export type CommandError = { type: "String"; message: string } | { type: "Anyhow"; message: string } | { type: "UnsupportedPlatform"; message: string } | { type: "Io"; message: string } | { type: "PathError"; message: string; variant: string } | { type: "Utf8Error"; message: string } | { type: "MutexLock"; message: string } | { type: "TauriError"; message: string } | { type: "TokioError"; message: string } | { type: "RegexError"; message: string } | { type: "DowncastError"; message: string } | { type: "WindowsError"; message: string } | { type: "ReqwestError"; message: string } | { type: "DownloadError"; message: string; variant: string } | { type: "IniParseError"; fileName: string | null; line: number; col: number; msg: string } | { type: "TranslationParseError"; key: string; filePath: string; fileName: string; line: number; column: number; message: string } | { type: "UrlParseError"; message: string }
export type DownloadProgress = { 
/**
 * Number of downloaded bytes formatted as a string, because the numbers might get too large for Json/IPC.
 */
downloadedBytes: string; 
/**
 * Size of downloaded file in number of bytes formatted as a string, because the numbers might get too large for Json/IPC.
 */
totalBytes: string; percent: number }
export type FcmAction = "installHud" | "installBridge" | "remove"
export type FcmChange = { path: string; description: string }
export type FcmPackageInfo = { version: string; source: string }
export type FcmPrerequisites = { provider: string | null; hudModLoader: boolean }
export type FcmPreview = { token: string; action: FcmAction; provider: string; installed: string | null; package: FcmPackageInfo | null; changes: FcmChange[] }
export type FileCategory = "main" | "update" | "optional" | "old_version" | "miscellaneous"
export type GameEdition = "Unknown" | "Steam" | "SteamPTS" | "Xbox" | 
/**
 * Legacy, for back-compat
 */
"MSStore" | 
/**
 * Legacy, for back-compat
 */
"BethesdaNet" | 
/**
 * Legacy, for back-compat
 */
"BethesdaNetPTS"
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type LaunchOption = "OpenURL" | "RunExec"
export type ModCopyMethod = "copy" | "symlink" | "hardlink"
/**
 * Settings that only apply to the mod manager portion of the tool.
 */
export type ModManagerSettings = { 
/**
 * The resource list (e.g. "sResourceArchive2List") to use.
 */
resourceList: string; 
/**
 * How to copy mod files.
 */
copyMethod: ModCopyMethod; 
/**
 * Where to put (new) mod resources in the order?
 */
resourceInsertionPosition: ResourceInsertionPosition; 
/**
 * Does not overwrite existing config files and also does not remove them.
 */
keepConfigFiles: boolean; 
/**
 * Where to download mods to?
 */
downloadPath: string; 
/**
 * Display NexusMods titles instead of mod names if available. User-preference.
 */
showNexusModsTitle: boolean }
export type NXMLinkDetails = { gameDomain: string; gameScopedId: number; fileId: number; key: string; expires: number; userId: number }
export type NXMNewLink = string
export type NexusModsAccountInfo = { profile: NexusModsProfile; rateLimit: NexusModsRateLimit }
export type NexusModsDownloadLink = { name: string; shortName: string; uri: string }
export type NexusModsFileUpdate = { oldFileId: number; newFileId: number; oldFileName: string; newFileName: string; uploadedTime: string }
export type NexusModsMembership = "Basic" | "Supporter" | "Premium"
export type NexusModsModFile = { id: number[]; uid: number; fileId: number; name: string; version: string; categoryId: number; categoryName: string; isPrimary: boolean; size: number; fileName: string; uploadedTime: string; modVersion: string; externalVirusScanUrl: string | null; description: string; sizeKb: number; sizeInBytes: string; changelogHtml: string | null; contentPreviewLink: string | null }
export type NexusModsModFiles = { fileUpdates: NexusModsFileUpdate[]; files: NexusModsModFile[] }
export type NexusModsProfile = { userId: number; apiKey: string; name: string; email: string; profileUrl: string; membership: NexusModsMembership }
export type NexusModsRateLimit = { dailyLimit: number; dailyRemaining: number; dailyReset: string; hourlyLimit: number; hourlyRemaining: number; hourlyReset: string }
export type NexusModsSSOAbort = null
export type NexusModsSSOUpdate = { apiKey: string } | { error: string } | "canceled"
export type Profile = { key: string; title: string; installationPath: string; modsPath: string; executableName: string; execParameters: string; launcherURL: string; iniPrefix: string; iniPath: string; gameEdition: GameEdition; launchOption: LaunchOption }
export type Profiles = { selected: string; profiles: Profile[] }
export type ResourceInsertionPosition = "prepend" | "append"
export type SerializableCommandResult<T> = { status: "ok"; value: T } | { status: "error"; value: CommandError }
export type Settings = { version: string; theme: Theme; useGameCursor: boolean; language: string | null; translationsLastUpdated: string | null; fetchServerStatusOnStart: boolean; checkForUpdatesOnStart: boolean; downloadTranslationsOnStart: boolean; quitOnGameLaunch: boolean; navigationCollapsed: boolean; modManager: ModManagerSettings; migratedFromV1?: SettingsMigration | null; prereleaseDismissed?: boolean | null }
export type SettingsMigration = { fromVersion: string; toVersion: string; date: string; dismissed: boolean }
export type Theme = "light" | "dark" | "system"
/**
 * Meta data and translation keys.
 */
export type Translation = { key: string; name: string; author: string; translation: { [key in string]: JsonValue } }
/**
 * Only meta data without the translation keys.
 */
export type TranslationMeta = { key: string; name: string; author: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
